theme: jekyll-theme-slate
title: Extended Print Management
show_downloads: true
github:
  zip_url: https://github.com/VentrisBM/Extended-Print-Management/archive/v1.1.zip
  tar_url: https://github.com/VentrisBM/Extended-Print-Management/archive/v1.1.tar.gz
