theme: jekyll-theme-slate
title: Extended Print Mangement
show_downloads: true
github:
  zip_url: https://github.com/VentrisBM/Extended-Print-Management/archive/v1.0.zip
  tar_url: https://github.com/VentrisBM/Extended-Print-Management/archive/v1.0.tar.gz
